apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-parcelize'
apply plugin: 'dagger.hilt.android.plugin'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdk = 36
    namespace 'com.unitpricecalculator'
    defaultConfig {
        applicationId "com.unitpricecalculator"
        minSdk = 24
        targetSdk = 36
        versionCode 36
        versionName "6.2.2"
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            pseudoLocalesEnabled true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        resources {
            excludes += [
                    'META-INF/DEPENDENCIES.txt', 'META-INF/DEPENDENCIES', 'META-INF/dependencies.txt',
                    'META-INF/LICENSE.txt', 'META-INF/LICENSE', 'META-INF/license.txt',
                    'META-INF/LGPL2.1', 'META-INF/NOTICE.txt', 'META-INF/NOTICE',
                    'META-INF/notice.txt', 'META-INF/ASL2.0'
            ]
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
        unitTests.includeAndroidResources = true
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ['-Xjvm-default=all']
    }
    lint {
        enable 'MissingTranslation'
    }
    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
}

def daggerVersion = "2.50" // Match hilt

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.google.guava:guava:33.1.0-android'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'com.squareup:otto:1.3.8'
    implementation "com.google.dagger:dagger:$daggerVersion"
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    kapt "com.google.dagger:dagger-compiler:$daggerVersion"
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.10.3'
    testImplementation 'org.mockito:mockito-core:3+' // modern mockito
    testImplementation 'com.google.truth:truth:1.4.2'
    testImplementation 'androidx.test:core:1.5.0'
    testAnnotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    implementation "com.google.dagger:hilt-android:$hiltVersion"
    kapt "com.google.dagger:hilt-compiler:$hiltVersion"
    testImplementation "com.google.dagger:hilt-android-testing:$hiltVersion"
    kaptTest "com.google.dagger:hilt-compiler:$hiltVersion"

    implementation("com.google.android.play:review:2.0.1")
    implementation("com.google.android.play:review-ktx:2.0.1")

    implementation platform('com.google.firebase:firebase-bom:32.7.4')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-analytics-ktx'
}

kapt {
    correctErrorTypes true
}

repositories {
    mavenCentral()
}
